on:
  push:
    branches:
      - main
env:
  PHAR_TOOL_VERSION: 1.4.0
  PHAR_TOOL_REPOSITORY: clue/phar-composer

permissions:
  contents: write
  pull-requests: write

name: Create Release

jobs:
  verify-release:
    uses: ./.github/workflows/php-package.yml
  release-please:
    needs: verify-release
    runs-on: ubuntu-24.04
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}
      info: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: php
  upload_phar:
    needs:
      - release-please
      - verify-release
    runs-on: ubuntu-24.04
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}-8.3
          path: mysql2jsonl
      - name: Print for debug release output
        run: echo ${{ needs.release-please.outputs.info }}
      - name: Release artifact
        run: gh release upload ${{ needs.release-please.outputs.tag }} mysql2jsonl
        env:
          GH_TOKEN: ${{ github.token }}
