on:
  push:
    branches:
      - main
env:
  DEFAULT_PHP_VERSION: 8.3

permissions:
  contents: write
  pull-requests: write

name: Create Release

jobs:
  verify-release:
    uses: ./.github/workflows/php-package.yml
  release-please:
    needs: verify-release
    runs-on: ubuntu-24.04
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}-${{ env.DEFAULT_PHP_VERSION }}
          path: mysql2jsonl
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: php
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./mysql2jsonl